name = "harnosandshf-events"
main = "src/index.js"
compatibility_date = "2025-08-13"

# You’ll add the route in the Cloudflare dashboard after import, so keep this simple.
[vars]
# Optional: lock CORS to your website (leave unset to allow "*")
# CORS_ORIGIN = "https://harnosandshf.se"
